### ISSUE TITLE
Use Configured Default Standard

### ISSUE THREAD

**Issue by jaswrks** [valeryan/vscode-phpcbf#3]
In this line:

https://github.com/valeryan/vscode-phpcbf/blob/b5840f98f7af4c9fd2aa6ff7b46d7aeb9bd27809/src/resolvers/standards-path-resolver.ts#L56

Shouldn't it default to `this.config.standard` when no ruleset is found? Instead it returns an empty string, ignoring the configured default standard in VS Code, and instead falling back on the PHPCS default standard. I think it should only be falling back on the PHPCS default standard when there is no standard configured in VS Code either.

**Comment by valeryan** [comment]
Hey, thanks for pointing that out. I will look at this and push out a fix.

**Comment by AdsonCicilioti** [comment]
Fix please! Nice extension.. Good work!

**Comment by valeryan** [comment]
I think I got the issue fixed for you. Feel free to reopen if it's still not working as expected.

**Comment by jaswrks** [comment]
Nice, thanks SO much. I'll try this out shortly and report back.
