### ISSUE TITLE
Exclude patterns ignored

### ISSUE THREAD

**Issue by brandonkal** [valeryan/vscode-phpcbf#8]
Exclude patterns defined in the root phpcs.xml file are ignored. Fix on save is enabled and phpcbf runs on changed files through VSCode. Running the same phpcbf from the command line, the file is correctly excluded and ignored.

**Comment by valeryan** [comment]
Hey Brandon, 

Thanks for pointing that out. I am aware temp file method does break the ignore pattern. It's not something that usually bothers me though. I will look into a way to fix the issue for you though. My thought is that it will be something like grabbing the ignore patterns from the config and comparing them to the file before running phpcbf or somehow passing the original file name along the phpcbf for its normal filter to pick up. While still trying to preserve the safety of the temp file.  I will find something that works for me.

**Comment by brandonkal** [comment]
Thank you.

phpcbf can manipulate standard input and there is an option to pass the original filename:
`--stdin-path=<stdinPath>`
So that may be an alternative approach to a temporary file. You would still be able to run some checks on the output. If everything works without error, write to the original file as usual.

I can see how this is quite an edge case (modifying files that must not match the project code style).
I ran into this issue with a config file for a third-party plugin. Since it is config, I like to have that in version control. However, the plugin also exposes an API to update the settings and it uses regex to do that. Editing it normally causes format on save, which then breaks the regex.

**Comment by valeryan** [comment]
That's what I am planning on playing with tomorrow. I have to do a little research on using stdin instead of a temp file and I will see how it works out.

**Comment by valeryan** [comment]
@brandonkal a new release is publishing to the marketplace right now. It should allow exclude patterns to work. If you have any problems let me know and reopen or create a new issue. Also, feel free to rate this extension on the marketplace. I currently have no ratings for reviews because I somehow blew this project away on the marketplace the other day.
